discordBotToken: ***REMOVED***
discordChannel: ***REMOVED***
discordAdminRole: ***REMOVED***
discordGuildID: ***REMOVED***
discordOwnerID: ***REMOVED***
dbhost: ***REMOVED***
dbuser: ***REMOVED***
dbpassword: ***REMOVED***