discordBotToken: ***REMOVED***
discordChannel: ***REMOVED***
discordAdminRole: ***REMOVED***
discordGuildID: ***REMOVED***
discordOwnerID: ***REMOVED***
startCommand: ***REMOVED***
csgoServerInstallPath: ***REMOVED***
steamCMDInstallPath: ***REMOVED***
serverLoginUsername: ***REMOVED***
serverLoginPassword: ***REMOVED***